---
- hosts: webservers
  become: true
  become_method: sudo
  vars_files:
    - vars/local.yml
  roles:
    - repo-epel
    - repo-remi
    - nginx
    - mysql
    - php
    - app.source
    - app.phpmyadmin
    - firewall  
