---
- hosts: web3
  become: true
  become_method: sudo
  vars_files:
    - vars/local.yml
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php
    - app.source
    - app.phpmyadmin
    - firewall  
